version: '2'
services:
  client:
    container_name: meghann_web_app
    build: 
      context: ./client
      dockerfile: Dockerfile
    volumes: 
      - './client:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
  server:
    container_name: meghann_server
    build: ./server
    ports:
      - '5000:5000'
